### ISSUE TITLE
Perform a single batch_mul in recursive IPA

### ISSUE THREAD

**Issue by maramihali** [AztecProtocol/barretenberg#1023]

**Comment by maramihali** [comment]
This might actually not be needed, closing for now

**Comment by zac-williamson** [comment]
heya I noticed this because it was referenced in the code still. I don't think it's useful because all of the scalars that go into the G mom would need to be multiplied by alpha_0 ...I think. In the recursive setting these are bigfield elements so very expensive.

I did make a PR that removes all of the isolated Commitment::operator* calls though and rolls them into the two batch_mul calls https://github.com/AztecProtocol/aztec-packages/pull/9420
